### ISSUE TITLE
Let's "source" not "bash" the install script

### ISSUE THREAD

**Issue by biochem-fan** [3dem/model-angelo#4]
In our cluster, we don't put `source /home1/software/packages/miniconda3/etc/profile.d/conda.sh` in `~/.bashrc` to avoid conflicts.

In this case,

```bash
source /home1/software/packages/miniconda3/etc/profile.d/conda.sh
bash install_script.sh --download-weights
```

does not work because we "[Can't execute conda activate from bash script](https://github.com/conda/conda/issues/7980)".

`conda activate model-angelo` _silently_ failed and installed Torch etc into the `base` environment. I didn't notice the issue until `pip` failed.

```
source install_script.sh --download-weights
```

did the trick.

(The messed up `base` environment was rolled back by `conda install --revision X` as explained [here](https://stackoverflow.com/questions/54172339/conda-install-screwed-up-my-environment-can-i-undo-it).)

**Comment by jamaliki** [comment]
That makes sense to me, I will change the readme. 

Thank you, Takanori!

**Comment by jamaliki** [comment]
Fixed

**Comment by biochem-fan** [comment]
Thank you very much for your quick fix.

**Comment by biochem-fan** [comment]
Hi, you missed the second occurrence of `bash install_script.sh` (for the cluster install).

**Comment by jamaliki** [comment]
Oh thanks!
