### ISSUE TITLE
RNA only does not run

### ISSUE THREAD

**Issue by mcianfrocco** [3dem/model-angelo#48]
Hello - 

I was testing my model-angelo v.1.0.1 installation using this RNA only cryo-EM map: 

https://www.rcsb.org/structure/6ues
https://www.emdataresource.org/EMD-20755

But, with this as input, the job won't start. Instead, it displays the help message.

Mike

$ model_angelo build -v emd_20755.mrc  -rf rcsb_pdb_6UES.fasta
usage: model_angelo build [-h] --volume-path VOLUME_PATH --protein-fasta PROTEIN_FASTA [--rna-fasta RNA_FASTA]
                          [--dna-fasta DNA_FASTA] [--output-dir OUTPUT_DIR] [--mask-path MASK_PATH] [--device DEVICE]
                          [--config-path CONFIG_PATH] [--model-bundle-name MODEL_BUNDLE_NAME]
                          [--model-bundle-path MODEL_BUNDLE_PATH] [--keep-intermediate-results]
model_angelo build: error: the following arguments are required: --protein-fasta/--fasta-path/--f/--pf/-f/-pf

**Comment by jamaliki** [comment]
Hi @mcianfrocco,

Yes, currently that is true. It's an oversight, hopefully should be fixed soon!

Best,
Kiarash.

**Comment by YaKohen** [comment]
Hi @jamaliki ,
Is there any progress on this? I'm still getting the same issue.
